<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="fragments/header.jspf" %>
<section class="page-heading"><div><p class="eyebrow">Academic administration</p><h1>${isEdit ? 'Edit' : 'Add'} ${moduleTitle}</h1></div><a class="button secondary" href="<c:url value='/web/${module}'/>">Back to list</a></section>
<section class="form-panel"><c:choose><c:when test="${isEdit}"><c:url var="formAction" value="/web/${module}/${record.id}"/></c:when><c:otherwise><c:url var="formAction" value="/web/${module}"/></c:otherwise></c:choose>
<form class="form-grid enterprise-form" action="${formAction}" method="post">
    <c:if test="${module != 'students' and module != 'student-enrollments' and module != 'program-subjects'}"><label>Code<input name="code" value="<c:out value='${record.code}'/>" maxlength="50" required></label><label>Name<input name="name" value="<c:out value='${record.name}'/>" maxlength="160" required></label></c:if>
    <c:if test="${module == 'students'}"><label>Registration number<input name="registrationNumber" value="<c:out value='${record.registrationNumber}'/>" maxlength="50" required></label><label>First name<input name="firstName" value="<c:out value='${record.firstName}'/>" maxlength="100" required></label><label>Middle name<input name="middleName" value="<c:out value='${record.middleName}'/>" maxlength="100"></label><label>Last name<input name="lastName" value="<c:out value='${record.lastName}'/>" maxlength="100" required></label><label>Email<input type="email" name="email" value="<c:out value='${record.email}'/>" maxlength="200"></label><label>Phone<input name="phone" value="<c:out value='${record.phone}'/>" maxlength="30"></label><label>Date of birth<input type="date" name="dateOfBirth" value="<c:out value='${record.dateOfBirth}'/>" max="<c:out value='${today}'/>"></label><label>Address<input name="address" value="<c:out value='${record.address}'/>" maxlength="500"></label></c:if>
    <c:if test="${module == 'student-enrollments'}"><label>Student<select name="studentId" required><option value="">Select student</option><c:forEach items="${students}" var="x"><option value="${x.id}" ${x.id == record.studentId ? 'selected' : ''}><c:out value="${x.registrationNumber}"/> — <c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'departments' or module == 'programs'}"><label>Faculty<select name="facultyId" required><option value="">Select faculty</option><c:forEach items="${faculties}" var="x"><option value="${x.id}" ${x.id == record.facultyId ? 'selected' : ''}><c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'programs'}"><label>Department<select name="departmentId" required><option value="">Select department</option><c:forEach items="${departments}" var="x"><option value="${x.id}" ${x.id == record.departmentId ? 'selected' : ''}><c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'sections' or module == 'program-subjects' or module == 'student-enrollments'}"><label>Program<select name="programId" required><option value="">Select program</option><c:forEach items="${programs}" var="x"><option value="${x.id}" ${x.id == record.programId ? 'selected' : ''}><c:out value="${x.code}"/> — <c:out value="${x.name}"/></option></c:forEach></select></label><label>Semester<select name="semesterId" required><option value="">Select semester</option><c:forEach items="${semesters}" var="x"><option value="${x.id}" ${x.id == record.semesterId ? 'selected' : ''}><c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'sections' or module == 'student-enrollments'}"><label>Academic year<select name="academicYearId" required><option value="">Select academic year</option><c:forEach items="${academicYears}" var="x"><option value="${x.id}" ${x.id == record.academicYearId ? 'selected' : ''}><c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'program-subjects'}"><label>Subject<select name="subjectId" required><option value="">Select subject</option><c:forEach items="${subjects}" var="x"><option value="${x.id}" ${x.id == record.subjectId ? 'selected' : ''}><c:out value="${x.code}"/> — <c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'student-enrollments'}"><label>Section<select name="sectionId" required><option value="">Select section</option><c:forEach items="${sections}" var="x"><option value="${x.id}" ${x.id == record.sectionId ? 'selected' : ''}><c:out value="${x.code}"/> — <c:out value="${x.name}"/></option></c:forEach></select></label></c:if>
    <c:if test="${module == 'semesters'}"><label>Sequence number<input type="number" min="1" name="sequenceNumber" value="<c:out value='${record.sequenceNumber}'/>"></label></c:if>
    <c:if test="${module == 'subjects'}"><label>Credit hours<input type="number" min="0" max="999.99" step="0.01" name="creditHours" value="<c:out value='${record.creditHours}'/>"></label></c:if>
    <c:if test="${module != 'students' and module != 'student-enrollments' and module != 'program-subjects'}"><label>Description<textarea name="description" rows="3"><c:out value="${record.description}"/></textarea></label></c:if>
    <label>Status<select name="status"><c:forEach items="${statuses}" var="value"><option value="${value}" ${value == record.status ? 'selected' : ''}>${value}</option></c:forEach></select></label>
    <c:if test="${isEdit}"><label>Remarks (optional)<textarea name="remarks" rows="2"></textarea></label></c:if>
    <div class="form-actions"><button class="primary" type="submit">${isEdit ? 'Update' : 'Create'} ${moduleTitle}</button><a class="button secondary" href="<c:url value='/web/${module}'/>">Cancel</a></div>
</form></section><%@ include file="fragments/footer.jspf" %>
