<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="fragments/header.jspf" %>
<section class="tenant-detail-hero">
    <div class="tenant-identity"><span class="tenant-avatar"><i class="fa-solid fa-graduation-cap" aria-hidden="true"></i></span><div><span class="eyebrow">Academic administration</span><h1>${moduleTitle} details</h1><div class="tenant-meta"><c:if test="${not empty record.code}"><span><i class="fa-solid fa-hashtag"></i><c:out value="${record.code}"/></span></c:if><c:if test="${not empty record.registrationNumber}"><span><i class="fa-solid fa-id-card"></i><c:out value="${record.registrationNumber}"/></span></c:if></div></div></div>
    <c:url var="recordListUrl" value="/web/${module}"><c:if test="${systemAdmin}"><c:param name="tenantId" value="${record.tenantId}"/></c:if></c:url><c:url var="recordEditUrl" value="/web/${module}/${record.id}/edit"><c:if test="${systemAdmin}"><c:param name="tenantId" value="${record.tenantId}"/></c:if></c:url>
    <div class="tenant-hero-actions"><span class="status-pill status-${record.status}"><c:out value="${record.status}"/></span><a class="button secondary" href="${recordListUrl}"><i class="fa-solid fa-arrow-left"></i>Back</a><a class="button primary" href="${recordEditUrl}"><i class="fa-solid fa-pen-to-square"></i>Edit</a></div>
</section>
<section class="tenant-info-panel"><div class="tenant-section-heading"><span><i class="fa-solid fa-circle-info"></i></span><div><h2>Record details</h2><p>Academic and student information</p></div></div><div class="tenant-detail-list">
    <c:if test="${systemAdmin}"><div><span>Tenant</span><strong><c:out value="${record.tenantName}"/></strong></div></c:if>
    <c:if test="${not empty record.name}"><div><span>Name</span><strong><c:out value="${record.name}"/></strong></div></c:if>
    <c:if test="${not empty record.firstName}"><div><span>Student name</span><strong><c:out value="${record.firstName}"/> <c:out value="${record.middleName}"/> <c:out value="${record.lastName}"/></strong></div></c:if>
    <c:if test="${not empty record.email}"><div><span>Email</span><strong><c:out value="${record.email}"/></strong></div></c:if><c:if test="${not empty record.phone}"><div><span>Phone</span><strong><c:out value="${record.phone}"/></strong></div></c:if>
    <c:if test="${not empty record.dateOfBirth}"><div><span>Date of birth</span><strong><c:out value="${record.dateOfBirth}"/></strong></div></c:if><c:if test="${not empty record.address}"><div><span>Address</span><strong><c:out value="${record.address}"/></strong></div></c:if>
    <c:if test="${not empty record.description}"><div><span>Description</span><strong><c:out value="${record.description}"/></strong></div></c:if><c:if test="${not empty record.creditHours}"><div><span>Credit hours</span><strong><c:out value="${record.creditHours}"/></strong></div></c:if><c:if test="${not empty record.sequenceNumber}"><div><span>Sequence</span><strong><c:out value="${record.sequenceNumber}"/></strong></div></c:if>
    <c:if test="${not empty record.facultyName}"><div><span>Faculty</span><strong><c:out value="${record.facultyName}"/></strong></div></c:if><c:if test="${not empty record.departmentName}"><div><span>Department</span><strong><c:out value="${record.departmentName}"/></strong></div></c:if><c:if test="${not empty record.programName}"><div><span>Program</span><strong><c:out value="${record.programName}"/></strong></div></c:if><c:if test="${not empty record.academicYearName}"><div><span>Academic year</span><strong><c:out value="${record.academicYearName}"/></strong></div></c:if><c:if test="${not empty record.semesterName}"><div><span>Semester</span><strong><c:out value="${record.semesterName}"/></strong></div></c:if><c:if test="${not empty record.subjectName}"><div><span>Subject</span><strong><c:out value="${record.subjectName}"/></strong></div></c:if><c:if test="${not empty record.sectionName}"><div><span>Section</span><strong><c:out value="${record.sectionName}"/></strong></div></c:if>
</div></section>
<section class="tenant-info-panel tenant-audit-panel"><div class="tenant-section-heading"><span><i class="fa-solid fa-clock-rotate-left"></i></span><div><h2>Entity Change Logs</h2><p>Recent changes recorded for this ${moduleTitle.toLowerCase()}</p></div></div><div class="table-wrap"><table class="data-table tenant-log-table"><thead><tr><th>When</th><th>Action</th><th>Field</th><th>Old value</th><th>New value</th><th>Remarks</th></tr></thead><tbody><c:forEach items="${changeLogs}" var="log"><tr><td><c:out value="${log.createdAt}"/></td><td><span class="log-action"><c:out value="${log.action}"/></span></td><td><c:out value="${empty log.fieldName ? '-' : log.fieldName}"/></td><td><c:out value="${empty log.oldValue ? '-' : log.oldValue}"/></td><td><c:out value="${empty log.newValue ? '-' : log.newValue}"/></td><td><c:out value="${empty log.remarks ? '-' : log.remarks}"/></td></tr></c:forEach><c:if test="${empty changeLogs}"><tr><td class="empty-cell" colspan="6">No entity change logs found.</td></tr></c:if></tbody></table></div></section>
<%@ include file="fragments/footer.jspf" %>
